"""Tests for the pure video I/O utilities in ``webapp.utils.video``.

Tests that touch a real OpenCV capture use a tiny synthetic video generated by
a pytest fixture (mirroring ``tests/test_pipeline.py``), so the suite needs no
sample assets, no GPU, and no network.  The pure index-selection logic is
exercised directly with no I/O at all.
"""

from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np
import pytest

from webapp.utils.video import (
    VideoInfo,
    equispaced_indices,
    extract_frames,
    get_video_info,
)

# ------------------------------------------------------------------
# Fixtures
# ------------------------------------------------------------------

NUM_TEST_FRAMES = 10
# Non-square so width/height swaps would be caught by the metadata test.
FRAME_W, FRAME_H = 64, 48
TEST_FPS = 25.0


@pytest.fixture()
def fake_video(tmp_path: Path) -> Path:
    """Create a minimal synthetic .mp4 video and return its path."""
    video_path = tmp_path / "input.mp4"
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(video_path), fourcc, TEST_FPS, (FRAME_W, FRAME_H))

    for i in range(NUM_TEST_FRAMES):
        frame = np.full((FRAME_H, FRAME_W, 3), fill_value=i * 25, dtype=np.uint8)
        writer.write(frame)

    writer.release()
    return video_path


# ------------------------------------------------------------------
# equispaced_indices — the pure core of the module
# ------------------------------------------------------------------


class TestEquispacedIndices:
    """The sampling contract: even spread, unique, sorted, edges avoided."""

    def test_sparse_sampling_spreads_and_avoids_edges(self):
        """n_samples << frame_count: 10 unique, strictly increasing, no edges."""
        frame_count, n_samples = 300, 10
        indices = equispaced_indices(frame_count, n_samples)

        assert len(indices) == n_samples
        assert len(set(indices)) == n_samples  # all unique
        assert indices == sorted(indices)  # ascending (with uniqueness → strict)
        assert all(0 <= i <= frame_count - 1 for i in indices)
        assert 0 not in indices
        assert frame_count - 1 not in indices

    def test_more_samples_than_frames_returns_every_index(self):
        """n_samples >= frame_count returns exactly list(range(frame_count))."""
        assert equispaced_indices(3, 5) == [0, 1, 2]

    def test_single_frame_returns_only_index_zero(self):
        """A one-frame video yields [0] regardless of n_samples."""
        assert equispaced_indices(1, 3) == [0]

    def test_non_positive_frame_count_raises(self):
        """frame_count <= 0 is a contract violation."""
        with pytest.raises(ValueError):
            equispaced_indices(0, 3)

    def test_non_positive_n_samples_raises(self):
        """n_samples <= 0 is a contract violation."""
        with pytest.raises(ValueError):
            equispaced_indices(10, 0)


# ------------------------------------------------------------------
# VideoInfo (pure dataclass)
# ------------------------------------------------------------------


class TestVideoInfo:
    """Pure tests for the metadata dataclass and its derived property."""

    def test_duration_seconds_divides_frames_by_fps(self):
        """Positive fps: duration is frame_count / fps."""
        info = VideoInfo(width=64, height=48, fps=25.0, frame_count=50)
        assert info.duration_seconds == pytest.approx(2.0)

    def test_duration_seconds_non_positive_fps_returns_zero(self):
        """Non-positive fps must not divide by zero; returns 0.0."""
        assert VideoInfo(width=64, height=48, fps=0.0, frame_count=10).duration_seconds == 0.0
        assert VideoInfo(width=64, height=48, fps=-1.0, frame_count=10).duration_seconds == 0.0


# ------------------------------------------------------------------
# get_video_info
# ------------------------------------------------------------------


class TestGetVideoInfo:
    """Metadata reading against a known synthetic video."""

    def test_reads_consistent_metadata(self, fake_video: Path):
        """Width/height/frame-count match the written video; duration ~ N/fps."""
        info = get_video_info(fake_video)

        assert isinstance(info, VideoInfo)
        assert info.width == FRAME_W
        assert info.height == FRAME_H
        assert info.frame_count == NUM_TEST_FRAMES
        assert info.duration_seconds == pytest.approx(NUM_TEST_FRAMES / TEST_FPS, rel=0.05)

    def test_missing_file_raises_filenotfound(self, tmp_path: Path):
        """A non-existent path must raise FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            get_video_info(tmp_path / "nonexistent.mp4")


# ------------------------------------------------------------------
# extract_frames
# ------------------------------------------------------------------


class TestExtractFrames:
    """Best-effort frame extraction for previews."""

    def test_extracts_requested_frames_in_order(self, fake_video: Path):
        """First / middle / last indices yield the right (H, W, 3) frames, in order."""
        indices = [0, NUM_TEST_FRAMES // 2, NUM_TEST_FRAMES - 1]
        frames = extract_frames(fake_video, indices)

        assert len(frames) == 3
        for idx, frame in zip(indices, frames, strict=True):
            assert isinstance(frame, np.ndarray)
            assert frame.shape == (FRAME_H, FRAME_W, 3)
            # The fixture fills frame i with the constant value i * 25, so the
            # frame mean pins both identity and order.  The tolerance absorbs
            # mp4v lossy compression (~3) while staying far below the 25-apart
            # neighbouring frames, so a wrong/duplicated/reordered frame fails.
            assert abs(float(frame.mean()) - idx * 25) <= 8

    def test_negative_indices_are_skipped(self, fake_video: Path):
        """Negative indices are dropped silently by the explicit guard."""
        frames = extract_frames(fake_video, [-5, 0, -1])

        assert len(frames) == 1
        assert frames[0].shape == (FRAME_H, FRAME_W, 3)

    def test_past_end_indices_are_skipped(self, fake_video: Path):
        """Positive indices beyond the last frame are dropped silently."""
        frames = extract_frames(fake_video, [0, NUM_TEST_FRAMES + 5])

        # Only the valid index 0 decodes; the past-end read returns no frame.
        assert len(frames) == 1
        assert frames[0].shape == (FRAME_H, FRAME_W, 3)

    def test_missing_file_raises_filenotfound(self, tmp_path: Path):
        """A non-existent path must raise FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            extract_frames(tmp_path / "nonexistent.mp4", [0])
